### ISSUE TITLE
Adequação de documentação

### ISSUE THREAD

**Issue by sfwygor-br** [sfwygor-br/engsys#5]
Detalhar os casos de uso:
- **SOLICITAÇÃO DE USO**
- **LOGIN**
- **CADASTRO DE USUÁRIOS**

Refazer os diagramas de sequência de acordo com as determinações da orientadora.
Corrigir Paginação.
Corrigir Sumário.
Alterar modelo antigo de telas para o novo modelo que será disponibilizado. 

Tarefa para você - @rafaelfer32

**Comment by rafaelfer32** [comment]
1. Acertado a paginação e sumário conforme solicitado pela orientadora.
2. Criado os casos de uso cadastro de usuários, login e solicitação de uso (faltando apenas criar no Asta para implementar no documento.
